apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{artifactId}}-dpl
  name: {{artifactId}}-dpl
spec:
  {{=<% %>=}}
  replicas: {{ .Values.Deployment.Replicas }}
  strategy: {}
  template:
    metadata:
      labels:
        <%={{ }}=%>
        name: {{artifactId}}-dpl
    spec:
      containers:
      - name: {{artifactId}}-dpl
        {{=<% %>=}}
        image: "{{ .Values.Docker.RegistryUri }}/{{ .Values.Docker.Image }}:{{ .Values.Docker.Tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15
          env:
          {{- if eq true .Values.AppDynamics.Enabled }}
              - name: APPDYNAMICS_CONTROLLER_HOST_NAME
                value: {{ .Values.AppDynamics.ControllerHost | quote }}
              - name: APPDYNAMICS_CONTROLLER_PORT
                value: {{ .Values.AppDynamics.ControllerPort  | quote }}
              - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
                value: {{ .Values.AppDynamics.ControllerSSL  | quote }}
              - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
                value: {{ .Values.AppDynamics.AccountName  | quote }}
              - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
                value: {{ .Values.AppDynamics.AccountKey  | quote }}
              - name: APPDYNAMICS_AGENT_APPLICATION_NAME
                value: {{ .Release.Name | quote }}
              - name: APPDYNAMICS_AGENT_TIER_NAME
                value: {{ .Values.AppDynamics.TierName  | quote }}
              - name: APPDYNAMICS_AGENT_NODE_NAME
                value: {{ .Values.AppDynamics.NodeName  | quote }}
              - name: APPDYNAMICS_NODE_PREFIX
                value: {{ .Values.AppDynamics.NodePrefix  | quote }}
              {{- end }}
                  resources:
                      limits:
                        memory: {{ .Values.Deployment.Memory.Limits }}
                        requests:
                            memory: {{ .Values.Deployment.Memory.Request }}
                  volumeMounts:
                  - name: application-properties
                  mountPath:  /config/application.properties
                  subPath: application.properties
                  volumes:
                  - name: application-properties
                  configMap:
                  name: application.properties
